export const CUBE_NAME = {
  RED_CUBE: '레드 큐브',
  BLACK_CUBE: '블랙 큐브',
  QUESTIONABLE_CUBE: '수상한 큐브',
  MASTER_CUBE: '명장의 큐브',
  CRAFTSMAN_CUBE: '장인의 큐브',
  KARMA_MASTER_CUBE: '카르마 명장의 큐브',
  KARMA_CRAFTSMAN_CUBE: '카르마 장인의 큐브',
  EVENT_RING_MASTER_CUBE: '이벤트 링 전용 명장의 큐브',
  QUESTIONABLE_ADDITIONAL_CUBE: '수상한 에디셔널 큐브',
  ADDITIONAL_CUBE: '에디셔널 큐브',
  WHITE_ADDITIONAL_CUBE: '화이트 에디셔널 큐브',
};

export const COMMON_CUBE = [
  CUBE_NAME.RED_CUBE,
  CUBE_NAME.CRAFTSMAN_CUBE,
  CUBE_NAME.EVENT_RING_MASTER_CUBE,
  CUBE_NAME.KARMA_CRAFTSMAN_CUBE,
  CUBE_NAME.KARMA_MASTER_CUBE,
  CUBE_NAME.MASTER_CUBE,
  CUBE_NAME.QUESTIONABLE_CUBE,
];

export const COMMON_ADDITIONAL_CUBE = [
  CUBE_NAME.ADDITIONAL_CUBE,
  CUBE_NAME.QUESTIONABLE_ADDITIONAL_CUBE,
];
